/**
 * Canonical registrable domains for aggregation (multi-region / sub-brand senders → one bucket).
 * Merged from Gmail import heuristics and import-candidate extraction.
 */
export const DOMAIN_CANONICAL: Readonly<Record<string, string>> = {
  "amazon.co.uk": "amazon.com",
  "amazon.de": "amazon.com",
  "amazon.fr": "amazon.com",
  "amazon.ca": "amazon.com",
  "amazon.com.au": "amazon.com",
  "primevideo.com": "amazon.com",
  "audible.com": "amazon.com",
  "uber.com": "uber.com",
  "uberinternal.com": "uber.com",
  "lyftmail.com": "lyft.com",
  "lyft.com": "lyft.com",
  "openai.com": "openai.com",
  "email.openai.com": "openai.com",
  /** Marketing mail often from facebookmail.com */
  "facebookmail.com": "meta.com",
};

/**
 * Human-readable provider title for a normalized domain (aggregation key).
 */
export const PROVIDER_LABELS: Readonly<Record<string, string>> = {
  "netflix.com": "Netflix",
  "spotify.com": "Spotify",
  "apple.com": "Apple",
  "amazon.com": "Amazon",
  "amazon.co.uk": "Amazon",
  "github.com": "GitHub",
  "google.com": "Google",
  "microsoft.com": "Microsoft",
  "adobe.com": "Adobe",
  "dropbox.com": "Dropbox",
  "notion.so": "Notion",
  "notion.com": "Notion",
  "figma.com": "Figma",
  "stripe.com": "Stripe",
  "paypal.com": "PayPal",
  "chase.com": "Chase",
  "bankofamerica.com": "Bank of America",
  "coinbase.com": "Coinbase",
  "discord.com": "Discord",
  "slack.com": "Slack",
  "zoom.us": "Zoom",
  "linkedin.com": "LinkedIn",
  "twitter.com": "X (Twitter)",
  "x.com": "X",
  "facebook.com": "Meta",
  "meta.com": "Meta",
  "instagram.com": "Instagram",
  "openai.com": "OpenAI",
  "uber.com": "Uber",
  "lyft.com": "Lyft",
  "airbnb.com": "Airbnb",
  "booking.com": "Booking.com",
  "expedia.com": "Expedia",
  "delta.com": "Delta",
  "united.com": "United Airlines",
  "southwest.com": "Southwest",
  "hulu.com": "Hulu",
  "disneyplus.com": "Disney+",
  "max.com": "Max",
  "paramountplus.com": "Paramount+",
  "docusign.com": "DocuSign",
  "mailchimp.com": "Mailchimp",
  "twilio.com": "Twilio",
  "vercel.com": "Vercel",
  "cloudflare.com": "Cloudflare",
  "digitalocean.com": "DigitalOcean",
  "heroku.com": "Heroku",
  "atlassian.com": "Atlassian",
  "jetbrains.com": "JetBrains",
};
